In [1]:
import pandas as pd
import numpy as np
import json

In [2]:
audi_file = pd.read_json('20180925101535_label3D_frontcenter_000011230.json')

In [3]:
audi_file

,box_0,box_1,box_2,box_3,box_4,box_5,box_6,box_7,box_8
2d_bbox,"[1083.448, 662.8432, 1285.339, 845.3809]","[1120.21, 689.4951, 1360.183, 894.4734]","[1157.44, 722.7399, 1511.514, 959.7899]","[893.7178, 601.361, 1073.844, 831.7234]","[656.8566, 614.9208, 886.7292, 827.2605]","[840.8017, 688.3874, 1133.932, 972.4118]","[431.73, 674.3155, 805.1379, 917.394]","[-159.8338, 660.5636, 705.3446, 1170.09]","[556.1852, 750.7253, 1404.197, 1444.811]"
3d_points,"[[21.055281647689508, -1.847072728745537, -1.8...","[[15.98135, -1.819799999999999, -1.88435], [19...","[[11.764003719419058, -1.814230754120784, -1.8...","[[19.551073543375992, 0.8294298787023181, -1.6...","[[21.827877602639052, 3.990666210821535, -1.74...","[[11.540688067170647, 0.8522495576519641, -1.8...","[[13.114622944602104, 4.147684603332797, -1.71...","[[6.314892815075765, 4.211920786160908, -1.714...","[[4.184936332268902, 1.011668915558196, -1.788..."
alpha,0,0,0,0,0,0,0,0,0
axis,"[7.381410761856192e-07, 7.381410761856192e-07,...","[1.0, 0.0, 0.0]","[0.0, 0.0, 1.0]","[2.403941020896206e-07, 2.403941020896206e-07,...","[3.9690508536559555e-07, 3.9690508536559555e-0...","[4.006191815017254e-07, 4.006191815017254e-07,...","[2.6297402010752e-06, 2.6297402010752e-06, 0.9...","[1.224964583595349e-06, 1.224964583595349e-06,...","[0.0, 0.0, 1.0]"
center,"[23.290400346484, -2.89027428010409, -0.822700...","[17.91635, -2.7798, -0.969349999999999]","[13.6893001118209, -2.79426075437815, -1.07599...","[21.9481516589311, -0.31671217221775905, -0.35...","[24.63289946565405, 2.6357298798457203, -0.447...","[13.653649105612299, -0.20368398667153, -0.945...","[15.759449911295999, 2.94827211538348, -0.81945]","[8.79934961100011, 2.975504824930489, -0.81500...","[6.53245001245654, -0.037725920207584, -1.058]"
class,Car,Car,Car,Car,Car,Car,Car,Car,Car
id,0,1,2,3,4,5,6,7,8
occlusion,2,2,1,2,1,2,1,0,1
rot_angle,0.0142748,0,0.0104001,0.0438345,0.026548,0.0263018,0.00400675,0.00860167,0.00238898
size,"[4.44, 2.15, 2.15]","[3.87, 1.92, 1.83]","[3.83, 2.0, 1.48]","[4.89, 2.08, 2.51]","[5.68, 2.56, 2.59]","[4.28, 2.0, 1.82]","[5.28, 2.42, 1.79]","[4.99, 2.43, 1.8]","[4.69, 2.11, 1.46]"
truncation,0,0,0,0,0,0,0,0,1

In [4]:
df = audi_file.loc[['center','class','id', 'rot_angle', 'size']]

In [5]:
df

,box_0,box_1,box_2,box_3,box_4,box_5,box_6,box_7,box_8
center,"[23.290400346484, -2.89027428010409, -0.822700...","[17.91635, -2.7798, -0.969349999999999]","[13.6893001118209, -2.79426075437815, -1.07599...","[21.9481516589311, -0.31671217221775905, -0.35...","[24.63289946565405, 2.6357298798457203, -0.447...","[13.653649105612299, -0.20368398667153, -0.945...","[15.759449911295999, 2.94827211538348, -0.81945]","[8.79934961100011, 2.975504824930489, -0.81500...","[6.53245001245654, -0.037725920207584, -1.058]"
class,Car,Car,Car,Car,Car,Car,Car,Car,Car
id,0,1,2,3,4,5,6,7,8
rot_angle,0.0142748,0,0.0104001,0.0438345,0.026548,0.0263018,0.00400675,0.00860167,0.00238898
size,"[4.44, 2.15, 2.15]","[3.87, 1.92, 1.83]","[3.83, 2.0, 1.48]","[4.89, 2.08, 2.51]","[5.68, 2.56, 2.59]","[4.28, 2.0, 1.82]","[5.28, 2.42, 1.79]","[4.99, 2.43, 1.8]","[4.69, 2.11, 1.46]"

In [6]:
schema = pd.DataFrame(index=range(len(df.columns)), columns = ['sample_id', 'object_id', 'center_x', 'center_y', 'center_z', 'width', 'length', 'height', 'angle', 'object_class', 'data_location_in_s3'])

In [7]:
schema["sample_id"]= '000011230'

In [8]:
for lab, row in df.iterrows():
    if lab == "center":
        center_x = []
        center_y = []
        center_z = []
        centers_array = df.loc["center"].values
        for i in range(len(centers_array)):
            center_x.append(centers_array[i][0])
            center_y.append(centers_array[i][1])
            center_z.append(centers_array[i][2])
        schema["center_x"]= center_x
        schema["center_y"]= center_y
        schema["center_z"]= center_z
    if lab == "class":
        schema["object_class"]= df.loc["class"].values
    if lab == "id":
        schema["object_id"] = df.loc["id"].values
    if lab == "rot_angle":
        schema["angle"] = df.loc["rot_angle"].values
    if lab == "size":
        width = []
        length = []
        height = []
        sizes_array = df.loc["size"].values
        for i in range(len(sizes_array)):
            width.append(sizes_array[i][0])
            length.append(sizes_array[i][1])
            height.append(sizes_array[i][2]) 
        schema["width"] = width
        schema["length"] = length
        schema["height"] = height

In [9]:
schema

,sample_id,object_id,center_x,center_y,center_z,width,length,height,angle,object_class,data_location_in_s3
0,000011230,0,23.290400,-2.890274,-0.82270,4.44,2.15,2.15,0.0142748,Car,NaN
1,000011230,1,17.916350,-2.779800,-0.96935,3.87,1.92,1.83,0,Car,NaN
2,000011230,2,13.689300,-2.794261,-1.07600,3.83,2.00,1.48,0.0104001,Car,NaN
3,000011230,3,21.948152,-0.316712,-0.35055,4.89,2.08,2.51,0.0438345,Car,NaN
4,000011230,4,24.632899,2.635730,-0.44740,5.68,2.56,2.59,0.026548,Car,NaN
5,000011230,5,13.653649,-0.203684,-0.94505,4.28,2.00,1.82,0.0263018,Car,NaN
6,000011230,6,15.759450,2.948272,-0.81945,5.28,2.42,1.79,0.00400675,Car,NaN
7,000011230,7,8.799350,2.975505,-0.81500,4.99,2.43,1.80,0.00860167,Car,NaN
8,000011230,8,6.532450,-0.037726,-1.05800,4.69,2.11,1.46,0.00238898,Car,NaN

In [10]:
export_csv = schema.to_csv (r'/home/ubuntu/autonomous-vehicles/export_dataframe.csv', index = None, header=True)